version: "3"
services:
    jenkins: 
      restart: unless-stopped
      image: hleb/jenkins-cloudbuilder
      ports:
        - 127.0.0.1:8080:8080
      environment:
        PRIVATE_REGISTRY_HOSTNAME: ${REGISTRY_DOMAIN}
      volumes:
        - ./data/jenkins/home:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
        - ./data/jenkins/bin:/var/jenkins_home/bin
        - ./data/jenkins/jobs:/var/jenkins_home/jobs
