#!/bin/bash

# security.groovy expects /var/run/secrets to be present and to contain settings for the original user
# this script allows insecure mode (e.g. for local testing), where credentials are set via environment variables or even omitted

set -e 

if [ -e /var/run/secrets ]; then exit 0 ; fi

# for persistence
PERSISTENT_DIR=/var/jenkins_home/jenkins_cloudbuilder_secrets
mkdir -p $PERSISTENT_DIR
ln -s $PERSISTENT_DIR /var/run/secrets

if [ -e /var/run/secrets/jenkins-user ] && [ -e /var/run/secrets/jenkins-pass ]; then
    exit 0;
fi

JENKINS_USER=${JENKINS_USER:-admin}
echo "Jenkins user: $JENKINS_USER" >&2

if [ -z "$JENKINS_PASS" ]; then
  JENKINS_PASS=$(pwgen)
  echo "WARNING: setting up autogenerated admin password $JENKINS_PASS" >&2
fi

echo "$JENKINS_USER" > /var/run/secrets/jenkins-user
echo "$JENKINS_PASS" > /var/run/secrets/jenkins-pass

chown jenkins:jenkins /var/run/secrets/jenkins-*
chmod 0440 /var/run/secrets/jenkins-*
